### ISSUE TITLE
Draw graphs from JS instead of using Google Sheets 

### ISSUE THREAD

**Issue by triedcatched** [covid19india/covid19india#11]
Data for graphs can be fetched with this link:
https://spreadsheets.google.com/feeds/cells/1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk/o6emnqt/public/values?alt=json

The above url is a json of the below sheet:
https://docs.google.com/spreadsheets/d/1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk/edit#gid=1544756290

**Comment by triedcatched** [comment]
Sample of graph done by Naveen here
https://github.com/s-naveen/covid19india

**Comment by sudevschiz** [comment]
@s-naveen 🙏
