### ISSUE TITLE
Adapt to new mock-up; Tiny plots under each number

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india#12]
One of our passionate frontend dev @suryaceg  has created this mock-up of how the site could look like. If someone could pick this up, develop and create a pull request, would love to merge these changes.

https://www.figma.com/file/fdi7MrRQJBrxAfJlnxygjK/COVID19-India-Ops-Website-Design?node-id=0:1

**Comment by suryaceg** [comment]
Here is the interaction flow 

[doc_2020-03-19_13-29-21.mp4.zip](https://github.com/BetaTurtle/covid19india/files/4353293/doc_2020-03-19_13-29-21.mp4.zip)

**Comment by akshitkr** [comment]
I'm on it.

**Comment by suryaceg** [comment]
@akshitkr dude, can you ping me in Telegram? 

@eyeofastorm

**Comment by suryaceg** [comment]
> I'm on it.

This has been already done by another volunteer. Please do not work on it.

**Comment by akshitkr** [comment]
@suryaceg alright great.

**Comment by suryaceg** [comment]
If you want to work on UI. Let me know. We are building a new site altogether. You can contribute for that.

**Comment by akshitkr** [comment]
alright sure
