### ISSUE TITLE
Add Covid19 patient's city of origin to the Data sheet

### ISSUE THREAD

**Issue by saurav-joshi** [covid19india/covid19india#25]
Datasheet already has a "Detected City" data field, this, however, may not be sufficient especially given the size of India. The most vulnerable city/village should be proactively identified which may help the testing as well.

**Comment by sudevschiz** [comment]
@tecoholic Should we consider this in the data model?

**Comment by tecoholic** [comment]
@sudevschiz Definitely. I will include it.

**Comment by tecoholic** [comment]
@sudevschiz On second thoughts, is this data viable to collect?
