### ISSUE TITLE
Use API to pull data instead of sheets

### ISSUE THREAD

**Issue by JunaidBabu** [covid19india/covid19india#27]
Currently the data is fetched from the raw json obtained from https://spreadsheets.google.com/feeds/cells/1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk/ovd0hzm/public/values?alt=json

The below API which can give all the data from above in a cleaner way must be used to create table and maps:
fetch data from https://api.covid19india.org/data.json

**Comment by triedcatched** [comment]
@s-naveen could you have a look into this?
Since you worked on the table sorting, it might be easier for you to shift it.

**Comment by s-naveen** [comment]
> @s-naveen could you have a look into this?
> Since you worked on the table sorting, it might be easier for you to handle this

Sure I'm on it.

**Comment by JunaidBabu** [comment]
Thanks @s-naveen for the prompt action. 
Merged and closed!
