### ISSUE TITLE
Add Weblinks

### ISSUE THREAD

**Issue by namanmodani** [covid19india/covid19india#33]
Append logos that link to our **Twitter** (already present), **Instagram** and **Facebook** handle in order to make it easier for the social team to propagate news and infographics in the general public.

**Comment by sudevschiz** [comment]
The Twitter button currently on the website gives the user an option to tweet the live stats. The tweet also contains the twitter handle @covid19indiaorg.

Isn't this enough for twitter - and more engaging?

The new version will have links to instagram and twitter.

**Comment by namanmodani** [comment]
Twitter's fine - do incorporate Instagram and FB though.
