### ISSUE TITLE
Add last 24 hour column to State-wise Data

### ISSUE THREAD

**Issue by roronoasoro** [covid19india/covid19india#8]
Add last 24 hour column to Confirmed, Recovered and Deaths to show count change for each state in the last 24 hour duration.

**Comment by sudevschiz** [comment]
@mohammedshafeeqet is fixing the data to reflect the states numbers correctly. After this, all the numbers would be directly updated from Raw Data. So this column could be added.

However, let's think again if this information is really required.

Will keep this open

**Comment by sudevschiz** [comment]
Sheet is fixed! Great work by Data team.

Please do discuss here if this is really required.
Issues that I see are : 
1. Do you mean 24-hour "window" or just the previous date
2. The current table is already tight in mobile view. Adding this column might make it illegible.
1.

**Comment by immortal3** [comment]
Please,also add delta in statewise.
delta = increase of daily cases

**Comment by sudevschiz** [comment]
This is quite doable now. The Raw Data has been validated at a state level by the data team.

Should we only show this for confirmed cases or for recovered and deceased cases. 

If you're interested in working on this, please ping @simulatedmonkey in the Telegram group.
