### ISSUE TITLE
Add Google Translate Widget

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india#9]
We should include Google Translate widget for translating the site. I will add the design for the placement of the translate icon.

**Comment by sudevschiz** [comment]
The amount of text in the website is very low. We would like to keep it that way. 

Maybe for the key numbers shown in the top, we can have a language switch? Then the question is which all languages do we support. I feel we shouldn't get into that cat-fight.

But if anybody has a solution and can make the changes and create a Pull Request, would be great

@triedcatched

**Comment by suryaceg** [comment]
So, another easy idea for this would be, publishing all the strings available in the website today in a Google Sheet & publish in the main Ops group for people to localize into the 18 official languages. We will push whichever language gets localised fully to the website. What do you think? @sudevschiz @triedcatched
